export const REGISTERUSER = "REGISTERUSER";
export const REGISTERBUSINESS = "REGISTERBUSINESS";
export const RECOVERYKEY = "RECOVERYKEY";
export const USERLOGIN = "USERLOGIN";
export const USERTOKEN = "USERTOKEN";
export const USERLOGINGOOGLE = "USERLOGINGOOGLE";
export const GET_RESTAURANTS = "GET_RESTAURANTS"
export const GET_MENUS = "GET_MENUS";
export const GET_MENUS_ADMIN = "GET_MENUS_ADMIN";
export const GET_MENUITEMS = "GET_MENUITEMS";
export const GET_MENUITEMS_ADMIN = "GET_MENUITEMS_ADMIN";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_ADMIN = "GET_CATEGORIES_ADMIN";
export const GET_RESTAURANTS_ALL ="GET_RESTAURANTS_ALL"
export const PUT_RESTAURANTS ="PUT_RESTAURANTS"
export const PUT_USERS ="PUT_USERS"
export const GET_USERS_ALL ="GET_USERS_ALL"
export const GET_ORDERS_ADMIN ="GET_ORDERS_ADMIN"
export const PUT_ITEMMENU ="PUT_ITEMMENU"
export const PUT_MENUS ="PUT_MENUS"

export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const GET_MENUITEMS_BYNAME = "GET_MENUITEMS_BYNAME";
export const SORTER_ASC = "SORTER_ASC";
export const CREATE_MENU = "CREATE_MENU";
export const CREATE_MENU_ITEMS = "CREATE_MENU_ITEMS"
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_USER = "UPDATE_USER";
export const CREATE_CATEGORIES = "CREATE_CATEGORIES";


//Carrito
export const CREATECOMPRA = "CREATECOMPRA";
export const CREATELISTAORDERSCOMPANY = "CREATELISTAORDERSCOMPANY"

export const CANCELARCOMPRAUSER = "CANCELARCOMPRAUSER"

export const IDCARRITOMERCADOPAGO = "IDCARRITOMERCADOPAGO"

//export const HAMBURGUER = 'HAMBURGUER'
export const LISTADOORDERSUSERS = "LISTADOORDERSUSERS"

//! EMpresa
export const EMPRESALOGIN = "EMPRESALOGIN"
export const UPDATE_USER_DATA = "UPDATE_USER_DATA"
export const SELECTRESTAURANTE = "SELECTRESTAURANTE"
export const GET_DETAIL_EMPRESA = "GET_DETAIL_EMPRESA"

//Admin
export const SET_TOKEN = "SET_TOKEN"
export const CLEAR_TOKEN = "CLEAR_TOKEN"